from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os
import datetime

def generate_pdf(student):
    if not os.path.exists("reports"):
        os.makedirs("reports")

    file_name = f"reports/{student['name']}_report.pdf"
    pdf = canvas.Canvas(file_name, pagesize=letter)

    # 🏫 College Name (Top)
    pdf.setFont("Helvetica-Bold", 16)
    pdf.setFillColor(colors.darkblue)
    pdf.drawCentredString(300, 760, "KALAIGNAR KARUNANIDHI INSTITUTE OF TECHNOLOGY")

    pdf.setFont("Helvetica", 10)
    pdf.setFillColor(colors.black)
    pdf.drawCentredString(300, 740, "Department of Computer Science")

    # 🖼️ Logo
    try:
        pdf.drawImage("logo.png", 40, 735, width=50, height=50)
    except:
        pass

    # 📅 Date
    date = datetime.datetime.now().strftime("%d-%m-%Y")
    pdf.drawString(400, 700, f"Date: {date}")

    # 🔥 WATERMARK (College Name)
    pdf.saveState()
    pdf.setFont("Helvetica-Bold", 40)
    pdf.setFillColorRGB(0.85, 0.85, 0.85)  # light grey
    pdf.translate(300, 400)
    pdf.rotate(45)
    pdf.drawCentredString(0, 0, "KKIT")
    pdf.restoreState()

    # 📄 Title
    pdf.setFont("Helvetica-Bold", 18)
    pdf.setFillColor(colors.black)
    pdf.drawCentredString(300, 700, "STUDENT REPORT")

    pdf.line(50, 690, 550, 690)

    # 👤 Student Info
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, 650, f"Name: {student['name']}")

    # 📊 Table Header
    pdf.setFillColor(colors.darkgreen)
    pdf.rect(50, 610, 500, 25, fill=1)

    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(60, 615, "Subject")
    pdf.drawString(350, 615, "Marks")

    # 📊 Table Data
    pdf.setFillColor(colors.black)
    pdf.setFont("Helvetica", 12)

    y = 580
    subjects = [
        ("Math", student['math']),
        ("Science", student['science']),
        ("English", student['english'])
    ]

    for sub, mark in subjects:
        pdf.drawString(60, y, sub)
        pdf.drawString(350, y, str(mark))
        y -= 30

    pdf.line(50, y+10, 550, y+10)

    # 📊 Calculations
    percentage = (student['total'] / 300) * 100

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y-20, f"Total: {student['total']}")
    pdf.drawString(50, y-50, f"Average: {student['average']:.2f}")
    pdf.drawString(50, y-80, f"Percentage: {percentage:.2f}%")

    # ✅ Result
    if percentage >= 50:
        result = "PASS"
        pdf.setFillColor(colors.green)
    else:
        result = "FAIL"
        pdf.setFillColor(colors.red)

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y-120, f"Result: {result}")

    # 🎨 Grade Color
    if student['grade'] == "A":
        pdf.setFillColor(colors.green)
    elif student['grade'] == "Fail":
        pdf.setFillColor(colors.red)
    else:
        pdf.setFillColor(colors.blue)

    pdf.drawString(300, y-120, f"Grade: {student['grade']}")

    # ✍️ Signature Section
    pdf.setFillColor(colors.black)

    pdf.line(50, 150, 200, 150)
    pdf.drawString(60, 130, "Class Teacher")

    pdf.line(350, 150, 500, 150)
    pdf.drawString(380, 130, "Principal")

    # Footer
    pdf.setFont("Helvetica-Oblique", 10)
    pdf.setFillColor(colors.grey)
    pdf.drawCentredString(300, 80, "Generated by PDF Report System")

    pdf.save()
    return file_name
